#!/usr/bin/env bash
#installs nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP' # enables firewall to port 80
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
