#!/usr/bin/env bash
#configure web server 2
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw default allow
sudo ufw allow 'Nginx HTTP'
echo "y" | sudo ufw enable
sudo sh -c 'echo "Holberton School for the win!" > /var/www/html/index.html'
sudo mkdir /var/www/html/redirect_me
new_string="rewrite ^/redirect_me/$ https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=43s permanent;"
sudo sed -i "/listen \[::\]:80 default_server;/a $new_string" /etc/nginx/sites-enabled/default
sudo touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "/listen \[::\]:80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-enabled/default
sudo sed -i "/listen \[::\]:80 default_server;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart
