#!/usr/bin/env bash
#signal cases
echo "$$" > "/var/run/holbertonscript.pid"
while :
do
    echo "To infinity and beyond"
    trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"; rm /var/run/holbertonscript.pid; exit' SIGINT
    trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT
done
